### ISSUE TITLE
Install the Microsoft Teams Meeting Add-in didn't work

### ISSUE THREAD

**Issue by Ide73** [Deyda/NeverRed#101]
I found the code to install the add-in on this blog
https://oberrauch.bz.it/2024/10/16/actual-quick-fixes-for-teams-2-0-vdi-pain-points/

There is a possible problem. When I try to install the add-in, the registration doesn’t work.

The issue is with lines 4 and 5.
msiexec.exe /i "$($installerPath.FullName)\MicrosoftTeamsMeetingAddinInstaller.msi" `
    Reboot=ReallySuppress ALLUSERS=1 TARGETDIR="C:\Windows\Microsoft\TeamsMeetingAddin" /qn

I changed it to one line with Start-Proces and waited until the process finished.
Start-Process -FilePath "msiexec.exe" -ArgumentList "/i `"$($installerPath.FullName)\MicrosoftTeamsMeetingAddinInstaller.msi`" Reboot=ReallySuppress ALLUSERS=1 TARGETDIR=`"C:\Windows\Microsoft\TeamsMeetingAddin`" /qn" -Wait

After I made the change, the script runs without errors and the registration works.
It seems to be a runtime problem. Server 2019

Best regards, Patrick Wagner

**Comment by Ide73** [comment]
![changedScript4TeamsOutlookAddin](https://github.com/user-attachments/assets/683a3824-b76d-4922-924f-aae412a7c640)
Copy-pasting changed the quotation marks.

**Comment by Deyda** [comment]
Solved in newest version
