### ISSUE TITLE
Google Chrome Enterprise x64 Stable Channel - Path Invalid

### ISSUE THREAD

**Issue by AP-Nick** [Deyda/NeverRed#103]
We've been having issues installing Google Chrome Enterprise x64 Stable channel, error from the log:

Path to MSI file (C:\Users\Admin\Downloads\NeverRed\Google Chrome\googlechromestandaloneenterprise_x64_Stable.msi) is invalid. Please check name and path
Error installing Google Chrome (Exit Code 1619 for file C:\Users\Admin\Downloads\NeverRed\Google Chrome\googlechromestandaloneenterprise_x64_Stable.msi)

**Comment by Deyda** [comment]
CAnnot recreate the issue with the newest version
