### ISSUE TITLE
Microsoft Teams 2 - Server 2019 - Windows Installer Popup

### ISSUE THREAD

**Issue by AP-Nick** [Deyda/NeverRed#104]
Windows Installer window up pops up during the upgrade process and will sit at the "Install Microsoft Teams 2 Add-In for Outlook" window until you click OK on the window. See attached screenshot.
![windows_installer](https://github.com/user-attachments/assets/15ad30a8-c8a1-4dfa-a2aa-fd261484059a)

Install Microsoft Teams 2 x64
Download Version: 24257.205.3165.02029
Current Version:
Update available
Starting install of Microsoft Teams 2 x64 version 24257.205.3165.02029
Windows Server 2019 detected. Installation without teamsbootstrapper.exe

Deployment Image Servicing and Management tool
Version: 10.0.17763.5830

Image Version: 10.0.17763.6414

The operation completed successfully.
Customize Microsoft Teams 2
Install Microsoft Teams 2 Add-In for Outlook

**Comment by Deyda** [comment]
Thx I will directly correct this

**Comment by Deyda** [comment]
Corrected :-)
