### ISSUE TITLE
Zoom VDI 

### ISSUE THREAD

**Issue by davisray1983** [Deyda/NeverRed#14]
Zoom VDI will show that it's downloading. 
Starting download of Zoom VDI version 5.11.2.21530
Download of the new version 5.11.2.21530 version finished!

Starting download of Zoom VDI ADMX files version 5.11.3
Download of the new ADMX files version 5.11.3 finished!

But it only download version .tx file and a Zoom VDI.log file.
In the Log file it returns this
Starting download of Zoom VDI version 5.11.2.21530
PS>TerminatingError(Invoke-WebRequest): "The remote server returned an error: (403) Forbidden."

I have tried it on 2 different networks to ensure no Firewall issues are occurring.

**Comment by Deyda** [comment]
Which PowerShell version is used??
PowerShell 5.1.22000.832 is used.
PowerShell 7 is not used and therefore the download of WebexVDI is unfortunately not possible.

---

Sry Ray I mean Zoom VDI not Webex...plz try PowerShell 7.

If u install it with NeverRed, my script detect this at the next run and recreate the Desktop Icon, that this is used the new installed PowerShell 7

**Comment by davisray1983** [comment]
Oh , ok I need powershell 7. My bad man. I will install that and do what
you said

**Comment by Deyda** [comment]
thx bro...i close the issue...if u have any probs...u know how to get me

**Comment by davisray1983** [comment]
Awesome, thanks man
