### ISSUE TITLE
MS 365 Apps 32bit

### ISSUE THREAD

**Issue by AchillesKem** [Deyda/NeverRed#18]
there seems to be an error in the Architecture Settings for MS 365.
Changing it to 32bit alters the install.xml to : 
- OfficeClientEdition="x86"
this is not working, correct is : 
- OfficeClientEdition="32"

Source (check the install.xml example) : https://learn.microsoft.com/en-us/deployoffice/overview-office-deployment-tool#download-the-installation-files-for-microsoft-365-apps

**Comment by Deyda** [comment]
The install.xml is filled with the correct one. I only show X64 and x86 in the GUI so it is consistent.

![image](https://user-images.githubusercontent.com/59874195/198265174-6745de2c-ecef-42fd-ac98-b9b305e91905.png)
