### ISSUE TITLE
Firefox ESR de-de is not downloading

### ISSUE THREAD

**Issue by MartinDiedenhofen** [Deyda/NeverRed#20]
The script shows that there is a new version of Firefox but the download don't start.

**********************
Starting download of Mozilla Firefox ESR German x64 version 102.4.0
INFO: @{TotalSize=0,00 Bytes; Time=00:00:00}
**********************

![grafik](https://user-images.githubusercontent.com/89959946/199715968-c6ef8a55-3dc2-4739-b51f-8e43fd45fb8b.png)

**Comment by Deyda** [comment]
Update to Version 2.09.16 will fix the error...
