### ISSUE TITLE
Citrix WorkspaceApp

### ISSUE THREAD

**Issue by MartinDiedenhofen** [Deyda/NeverRed#21]
Hi, 
there's a problem with the WorspaceApp. It's already the newest version installed and the Scipt shows it wrong for download.
![grafik](https://user-images.githubusercontent.com/89959946/199910207-1d042d16-3117-462c-8448-4a7e52c22fc1.png)

At the install part the script shows the current version correct but install the older version.
![grafik](https://user-images.githubusercontent.com/89959946/199910956-65c63a39-0f06-4201-a99c-4ceb39e86be1.png)

**Comment by Deyda** [comment]
Done with Version 2.09.17
