### ISSUE TITLE
Appears to be a version number tracking issue with currently installed software.

### ISSUE THREAD

**Issue by sparkstack1** [Deyda/NeverRed#30]
Steps to reproduce.

Have latest version of NeverRed.
Use NeverRed to Install latest version of teams machine based install.  It reports as version 1.6.00.1381

Rerun the NeverRed script.  Watch as it identifies the downloadable version as 1.6.00.01381 (adding a leading zero to last octet) and so decides the available version is newer, downloads, uninstalls, installs the "new" release.

<img width="641" alt="Screenshot 2023-03-07 at 1 10 10 PM" src="https://user-images.githubusercontent.com/97652274/223526197-8bdc507a-2f47-40e7-ba44-f905d4e595ae.png">

**Comment by Deyda** [comment]
Resolve in Version 2.10.07
