### ISSUE TITLE
Version 2.10.06 - Zoom does not download.

### ISSUE THREAD

**Issue by sparkstack1** [Deyda/NeverRed#31]
Steps to reproduce:

launch powershell 7 as an admin.  Run the NeverRed Script.
Select Zoom VDI. Click Start.
Watch as the script creates a folder and version related text files, but does not download the executable.

<img width="931" alt="Screenshot 2023-03-07 at 2 41 57 PM" src="https://user-images.githubusercontent.com/97652274/223547630-5d6b56d0-62f4-45e4-8cac-a7c762f7af9f.png">

**Comment by Deyda** [comment]
Resolved in Version 2.10.08

**Comment by sparkstack1** [comment]
It still seems to be broken with 2.10.08...  Filezilla also does the same thing..

<img width="919" alt="Screenshot 2023-03-07 at 3 13 25 PM" src="https://user-images.githubusercontent.com/97652274/223554218-b3f35e6d-667b-474c-b41a-1a6542cfdf6a.png">

<img width="923" alt="Screenshot 2023-03-07 at 3 09 55 PM" src="https://user-images.githubusercontent.com/97652274/223553984-cdc0186b-1c90-4005-a4e3-6f27e28ccd20.png">
