### ISSUE TITLE
Option to turn of Citrix regkeys for Teams installation

### ISSUE THREAD

**Issue by Rhavien** [Deyda/NeverRed#33]
Hi there!
Would it be possible to add the option to not add the citrix specific regkeys when installing Microsoft Teams?
We recently deployed an Azure Virtual Desktop environment using the neverred script to install the host software for the most part and wondered, why we didn't get the AVD optimisation in Teams to work. Turns out that Teams first checks for the Citrix specific regkeys and tries to set up the HDX optimisation. AVD optimisation gets ignored after this. It's happening in line 26677 in the nverred script. 
Further I want to ask, if you could even implement the registry key needed for AVD as an option? This is the link where the regkey is described: https://learn.microsoft.com/en-us/azure/virtual-desktop/teams-on-avd#enable-media-optimization-for-teams
Greetings and thank you!

**Comment by Deyda** [comment]
Solved in Version 2.10.15
