### ISSUE TITLE
No new version available in the internet. Seems to be occurring for a majority of apps.

### ISSUE THREAD

**Issue by WiseK** [Deyda/NeverRed#43]
Running NeverRed with Whatif and Report shows a lot of software that has No New Versions available in the internet however there are new versions available.

Citrix WorkspaceApp Current
Internet Version:
Downloaded Version:
Installed Version:  23.03.0.55
No new version available in the internet

Microsoft Azure CLI
Internet Version:
Downloaded Version:
Installed Version:  2.37.0
No new version available in the internet

Microsoft Azure Data Studio Insider x64 Per Machine
Internet Version:
Downloaded Version:
Installed Version:  1.35.0
No new version available in the internet

Git for Windows x64
Internet Version:
Downloaded Version:
Installed Version:  2.37.0
No new version available in the internet

Adobe Reader DC English x64
Internet Version:
Downloaded Version:
Installed Version:  23.001.20174
No new version available in the internet

WinSCP
Internet Version:
Downloaded Version:
Installed Version:  5.21.8
No new version available in the internet

**Comment by Deyda** [comment]
solved with newest version
