### ISSUE TITLE
Add support for PSWindowsUpdate

### ISSUE THREAD

**Issue by haavarstein** [Deyda/NeverRed#46]
PSWindowsUpdate is among Top 10 downloads on PowerShell Gallery. Would be nice to add an option to run it at the end of the application patching.

[Install-Module -Name PSWindowsUpdate](https://github.com/haavarstein/Applications/blob/master/Scripts/WindowsUpdate.ps1)

**Comment by Deyda** [comment]
Thx Eric. I will tinker this the next days 🤘🏽🤘🏽🤘🏽

**Comment by Deyda** [comment]
It's now implemented 
![image](https://github.com/Deyda/NeverRed/assets/59874195/9b26069c-864d-449c-a9f4-5ac3a6a5da9a)
with Version 2.10.17
