### ISSUE TITLE
FileZilla fails te download

### ISSUE THREAD

**Issue by rolfvantrigtcapgemini** [Deyda/NeverRed#54]
FileZilla fails to download and install

Filezilla Version: 3.65.0
Neverred version: 2.10.17

**********************
Windows PowerShell transcript start
Start time: 20230721174224
Username: XXX
RunAs User: XXXX
Configuration Name: 
Machine: XXXX (Microsoft Windows NT 10.0.17763.0)
Host Application: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -noexit -ExecutionPolicy Bypass -file C:\Program Files\XXXXX\NeverRed\NeverRed.ps1
Process ID: 10284
PSVersion: 5.1.17763.3770
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.17763.3770
BuildVersion: 10.0.17763.3770
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
**********************
Starting download of Filezilla version 3.65.0
PS>TerminatingError(Invoke-WebRequest): "Forbidden
You don't have permission to access this resource."
**********************
Windows PowerShell transcript end
End time: 20230721174225
**********************

**Comment by rolfvantrigtcapgemini** [comment]
Download Filezilla
Download Version: 3.65.0
Current Version:
Update available
Starting download of Filezilla version 3.65.0
PS>TerminatingError(Invoke-WebRequest): "Forbidden
You don't have permission to access this resource."
Download of the new version 3.65.0 finished!

**Comment by Deyda** [comment]
Solved with the newset version
