### ISSUE TITLE
Issue with controlup versioning.

### ISSUE THREAD

**Issue by sparkstack1** [Deyda/NeverRed#57]
Download ControlUp Agent ×64
Download Version: 8.8.0.1012
Current Version: 8.8.0.992
No new version available

^^ above message from latest release of NeverRed, which is incorrect.

**Comment by Deyda** [comment]
It works now with the latest version.

**Comment by sparkstack1** [comment]
It is still broken.  Latest version in use.

![Screenshot 2023-11-02 at 2 35 58 PM](https://github.com/Deyda/NeverRed/assets/97652274/ed959806-d86c-4901-9477-9766d73cc416)
