### ISSUE TITLE
Citrix Workspace Current Version Download not working

### ISSUE THREAD

**Issue by sredlin** [Deyda/NeverRed#60]
![image](https://github.com/Deyda/NeverRed/assets/20725533/0c048bf6-ee82-4141-8153-e667ef0897e1)

Citrix folder was created
Subfolder ReceiverCleanupUtility was created, and ReceiverCleanupUtility.exe was downloaded

Citrix WorkspaceApp Current folder was created but Citrix WorkspaceApp was not downloaded

**Comment by Deyda** [comment]
Solved in 2.10.21
