### ISSUE TITLE
Kein Problem, aber eine Frage zu einem Feature :D 

### ISSUE THREAD

**Issue by cromaki** [Deyda/NeverRed#7]
Hallo,

gäbe es die Möglichkeit, eine E-Mail Benachrichtigung zu implementieren? Denn wenn man viele Maschinen hat, wäre es cool benachrichtigt zu werden, was er aktualisiert hat und dass er natürlich überhaupt was getan hat.

Liebe Grüße
Marko

**Comment by Deyda** [comment]
Version 2.09.05 - Log ist unter \NeverRed\_Global Logs\GlobalLog.log zu finden

**Comment by Deyda** [comment]
Sehr gute Idee. Hatte mit Datum rumgespielt. Aber das gefällt mir noch besser. Gib mir ne halbe Stunde 🤘🏽

**Comment by Deyda** [comment]
Done. Have fun
