### ISSUE TITLE
NeverRed Updater

### ISSUE THREAD

**Issue by v1-valux** [Deyda/NeverRed#70]
I kind of need the possibility to update NeverRed before running..
Did not find anything here quickly so I wrote a little powershell script:

```
$zipUrl = "https://github.com/Deyda/NeverRed/archive/refs/heads/master.zip"
$zipFileNameNoExt = "NeverRed-master"
$extractPath = "D:\Scripts\NeverRed"

(New-Object System.Net.WebClient).DownloadFile($zipUrl, "$extractPath\$zipFileNameNoExt.zip")
Expand-Archive -Path $extractPath\$zipFileNameNoExt.zip -DestinationPath $extractPath -Force
Get-ChildItem -Path "$extractPath\$zipFileNameNoExt" -File | Move-Item -Destination "$extractPath\" -Force
Remove-Item "$extractPath\$zipFileNameNoExt" -Force -Recurse
```

totally can be optimized but that was sufficient for me.

Did I miss something altogether?

**Comment by Deyda** [comment]
Thescript has an auto update function...why we need it before start ? :-)

**Comment by v1-valux** [comment]
Mhm, strange.. it was still mentioning a newer version after I started it a multiple.
So is the update done by just running the NeverRed.ps1?
Or did I modify the shortcut wrongly?

Many thanks for the hint anyways :)

**Comment by Deyda** [comment]
Ony run the script, adn the he ask u, do u want an update...yes and he download and replace all the files :-)

**Comment by v1-valux** [comment]
Well, then we need to have a look why it didn't work.. (maybe AV or sth..)
Consider this issue closed :)

Thanks for your great work!
o7
