### ISSUE TITLE
Chrome download failing

### ISSUE THREAD

**Issue by dannyboyayyo** [Deyda/NeverRed#72]
![Screenshot 2024-01-28 170845](https://github.com/Deyda/NeverRed/assets/155789707/678b462c-69c2-4546-8169-ec37a0316f85)

**Comment by Boss-man** [comment]
omahaproxy.appspot.com is shut down.  Are you using the newest version of the script ?

**Comment by Deyda** [comment]
Newest Version no problem

**Comment by dannyboyayyo** [comment]
Using the latest 2.10.21 version and still have the error
