### ISSUE TITLE
"Teams Meeting AddIn for Microsoft Outlook" scheduled task does not register on non-english OS

### ISSUE THREAD

**Issue by TimThemannFKS** [Deyda/NeverRed#74]
The new "Teams Meeting AddIn for Microsoft Outlook" scheduled task does not register on non-english OS because the "-GroupId"-Parameter used by New-ScheduledTaskPrincipal seems to be language specific (changing "Users" to "Benutzer" cures the problem on a german-language OS).

**Comment by Deyda** [comment]
Thx i will correct this...It was a hard night

**Comment by TimThemannFKS** [comment]
;-) Thanks a lot for your work!

**Comment by TimThemannFKS** [comment]
$UsersSID = New-Object System.Security.Principal.SecurityIdentifier("S-1-5-32-545")
$Users = $UsersSID.Translate([System.Security.Principal.NTAccount])
$UsersName = $Users.Value 
$UsersName

**Comment by Deyda** [comment]
Thx and done in newest version
