### ISSUE TITLE
Microsoft Teams incorrectly uninstalled when no new msi is present 

### ISSUE THREAD

**Issue by VITGEnkah** [Deyda/NeverRed#76]
_NeverRed - Update your Software, the lazy way
      Manuel Winkel - Deyda Consulting (www.deyda.net)
                      Version 2.10.26

Is there a newer NeverRed version?
OK, NeverRed is newest version!

Does the script run under admin rights?
OK, script is running with admin rights.

Which PowerShell version is used??
PowerShell 5.1.17763.5458 is used.
PowerShell 7 is not used and therefore the download of ZoomVDI is unfortunately not possible.

Software selection
GUI Mode
Software selection done.

Selected Global Mode.
Global Language is English.
Global Architecture is x64.
Global Installer Type is Machine Based.

Selected Options.
Download Option Enabled.
Install Option Enabled.
What If Option Disabled.
Installer Repository Option Disabled.
Installer Clean Up Option Disabled.
Start Menu Clean Up Option Disabled.
Report Mode Option Disabled.
No NeverRed Icon Option Enabled.
Windows Update Option Disabled.

Install / Update PowerShell module!
Check Evergreen module version.
Update Evergreen module.
Update Evergreen module done.

Check Nevergreen module version.
Update Nevergreen module.
Update Nevergreen module done.

Check VcRedist module version.
Update VcRedist module.
Update VcRedist module done.

Check PSWindowsUpdate module version.
Update PSWindowsUpdate module.
Update PSWindowsUpdate module done.

Starting downloads...

Download Microsoft Teams Machine Based General ring x64
Download Version:
Current Version:
No new version available

Change User Mode to Install.

Starting installs...

Install Microsoft Teams Machine Based General ring x64
Download Version:
Current Version:  1.7.00.06058
Update available
Uninstall Microsoft Teams Machine Based
Uninstall Microsoft Teams Machine Based finished!
Starting install of Microsoft Teams Machine Based General ring x64 version
**Path to MSI file (C:\_admin\NeverRed\Microsoft Teams Machine Based\Teams_x64_General.msi) is invalid. Please check name and path**
Error installing Microsoft Teams Machine Based (Exit Code 1619 for file C:\_admin\NeverRed\Microsoft Teams Machine Based\Teams_x64_General.msi)
Customize Microsoft Teams Machine Based
Register Microsoft Teams Machine Based Add-In for Outlook
Error when customizing Microsoft Teams Machine Based (Error: Cannot index into a null array.)

Disable Change User Mode Install._

**Comment by Deyda** [comment]
Solved with Version 2.10.27
