### ISSUE TITLE
Power BI desktop not downloading

### ISSUE THREAD

**Issue by chezzer64** [Deyda/NeverRed#79]
Looks like Microsoft changed the Power BI download website which means the code to extract the Power BI Desktop version now fails with 404 error. 

I opened a similar issue on the Nevergreen repo:
[Nevergreen Issue #60](https://github.com/DanGough/Nevergreen/issues/60)

**Comment by Deyda** [comment]
Nope this works for me, because i dont use the nevergreen command for that. I used my own :-)

![image](https://github.com/Deyda/NeverRed/assets/59874195/cb0dc7e6-0966-4835-bb4d-c9fcbdf445e9)
