### ISSUE TITLE
New Teams teamsbootstrapper.exe doesn't download on first NeverRed run.

### ISSUE THREAD

**Issue by chezzer64** [Deyda/NeverRed#81]
On a machine where NeverRed has not been run before to download/install New Teams, the teamsbootstrapper.exe fails to download on the initial run of NeverRed due to the `"$PSScriptRoot\$Product\Microsoft Teams 2"` directory not having been created at that point. The result is that the New Teams install subsequently fails (on non Win Server 2019 OS) as teamsbootstrapper.exe is missing.

Suggest the following fix - change the following code:

```
            If ($WhatIf -eq '0') {
                Get-Download "https://go.microsoft.com/fwlink/?linkid=2243204&clcid=0x409" "$PSScriptRoot\$Product\" teamsbootstrapper.exe
            }
```

to:

```
            If ($WhatIf -eq '0') {
                If (!(Test-Path -Path "$PSScriptRoot\$Product")) { New-Item -Path "$PSScriptRoot\$Product" -ItemType Directory | Out-Null }
                Get-Download "https://go.microsoft.com/fwlink/?linkid=2243204&clcid=0x409" "$PSScriptRoot\$Product\" teamsbootstrapper.exe -includeStats
            }

```

**Comment by Deyda** [comment]
Thx..Correction in Version 2.10.33
