### ISSUE TITLE
Citrix Workspace App version comparison

### ISSUE THREAD

**Issue by jpmoock** [Deyda/NeverRed#82]
In the current version of the script (2.10.32), the downloaded version of the LTSR app is returned as 24.02.0.172, while the installed version is returned as 24.2.0.172.  This results in the Citrix Workspace LTSR app being reinstalled unecessarily.

I believe this is happening because of a typo in the code that pads the version string with leading zeroes for the $WSA variable in the Citrix WorkspaceApp section.

The $Version variable calculation in the Download Citrix WorkspaceApp section contains the following code, which functions correctly:
`$CurrentWSAStringLast = ([regex]::Matches($CurrentWSASplit[3], "." )).count`

The $WSA variable calculation in the Download Citrix WorkspaceApp section appears to have a typo in the $CurrentWSAStringLast variable (it should use $CurrentWSASplit[3] instead of $CurrentWSASplit[1]):
`$CurrentWSAStringLast = ([regex]::Matches($CurrentWSASplit[1], "." )).count`

**Comment by Deyda** [comment]
Correction in Version 2.10.33
