### ISSUE TITLE
GIMP channel support added to EverGreen breaks NeverRed

### ISSUE THREAD

**Issue by TimThemannFKS** [Deyda/NeverRed#85]
The GIMP team changed GIMPs versioning scheme and they introduced different release channels. For some reason, the changes made to the EverGreen script in order to support these changes (see https://github.com/aaronparker/evergreen/commit/f1614ef41f344fd923f5310efe9905e194bdf03c and https://github.com/aaronparker/evergreen/issues/639) break the GIMP functionality in NeverRed.

**Comment by Deyda** [comment]
Solved in Version 2.10.37
