### ISSUE TITLE
Zoom Download Error

### ISSUE THREAD

**Issue by MartinDiedenhofen** [Deyda/NeverRed#9]
Hallo, ich bekomme immer folgenden Fehler wenn ich das "Zoom Citrix Media Plugin" installieren möchte. 

Die Einstellungen im Script bei General sind:
![grafik](https://user-images.githubusercontent.com/89959946/152493858-ae7dc477-0119-4aa6-a44b-c85010d04cfd.png)

Die Einstellungen im Script bei Detail sind:
![grafik](https://user-images.githubusercontent.com/89959946/152493963-66087a44-c50a-4d04-8bd4-b5c5e6c6041f.png)

Dann kommt leider dieser Fehler:
![grafik](https://user-images.githubusercontent.com/89959946/152493673-53e31c71-5e37-4860-b2fb-9e26d9091b77.png)

Was mache ich falsch?

Danke und viele Grüße

**Comment by Deyda** [comment]
Die neuste Version ist hinterlegt.
