### ISSUE TITLE
Acrobat Reader DC (x64 / German) - Download fails

### ISSUE THREAD

**Issue by benni1972** [Deyda/NeverRed#92]
Nerverred tries to fix the Download URL for Acrobat Reader DC, at least for German language and x64 architecture.

Evergreen Download-URI for this is (currently):
"https://ardownload2.adobe.com/pub/adobe/acrobat/win/AcrobatDC/2400220965/AcroRdrDCx642400220965_de_DE.exe"

On line 17012, the script is trying to "generate" a x64 download-URL by replaceing "AcroRdrDC" with "AcroRdrDCx64".
As x64 is already part of the url, the replacement doubles the "x64"-part and hence creates an invalid Download-URL.
"https://ardownload2.adobe.com/pub/adobe/acrobat/win/AcrobatDC/2400220965/AcroRdrDCx64x642400220965_de_DE.exe"

So the download fails.

Please check the fix, that was implemented on 01.08.2024 ... maybe caused the current issue.

**Comment by Deyda** [comment]
Yes with the newest version this is solved. I push it later this day

**Comment by Deyda** [comment]
Solved with 2.10.42
