### ISSUE TITLE
Filezilla dropped from Evergreen Library

### ISSUE THREAD

**Issue by benni1972** [Deyda/NeverRed#93]
Seems that Filezilla is no longer in the evergreen app library (why?)

`Get-EvergreenApp -Name Filezilla

Please list supported application names with Find-EvergreenApp.
Find out how to contribute a new application to the Evergreen project at: https://stealthpuppy.com/evergreen/.

'Filezilla' not found. Evergreen supports these similar applications:
No applications match 'Filezilla'`

**Comment by Deyda** [comment]
I will tinker my own way. Thx for the info

**Comment by benni1972** [comment]
Confirmed working
 
[Version 2.10.53 - Change FileZilla DL to hardcoded address / Correction of teamsbootstrapper dl](https://github.com/Deyda/NeverRed/commit/d326aaffe5b59e1517fda699ab19cfe1fbd49815)
